// src/lib/components/SideBar.svelte
<script lang="ts">
  import * as Sidebar from "$lib/components/ui/sidebar/index.js";
  import { useSidebar } from "$lib/components/ui/sidebar/index.js";
  import * as Collapsible from "$lib/components/ui/collapsible/index.js";
  import { ModeWatcher, setMode } from "mode-watcher";
  
  import { 
    House, 
    BookOpen, 
    UserRound, 
    ChevronUp, 
    ChevronDown,
    PanelLeftClose,
    PanelLeft
  } from "lucide-svelte";

  import tasks from "$lib/data/tasks.json";
  import { goto } from "$app/navigation";
  import { page } from "$app/stores";
  import { browser } from "$app/environment";
  import { asset, resolve } from "$app/paths";

  // Get sidebar context
  const sidebar = useSidebar();
  
  // Safe access to sidebar state
  let isOpen = $derived(browser && sidebar ? sidebar.open : true);

  // Group tasks by category
  const tasksByCategory = $derived(
    Object.entries(
      tasks.reduce((acc, task) => {
        const category = task.category ?? "Uncategorized";
        (acc[category] ||= []).push(task);
        return acc;
      }, {} as Record<string, typeof tasks>)
    )
  );

  // Navigation helpers
  function navigateToHome(e: MouseEvent) {
    e.preventDefault();
    goto(resolve('/'));
  }

  function navigateToTask(title: string) {
    return (e: MouseEvent) => {
      e.preventDefault();
      goto(resolve('/task/[title]', { title }));
    };
  }

  // Check if current route is active
  function isActive(path: string) {
    return $page.url.pathname === path;
  }

  // Toggle sidebar
  function handleToggle() {
    if (browser && sidebar) {
      sidebar.toggle();
    }
  }

// Theme state
let currentMode: "light" | "dark" = "light";
function toggleMode() { 
  const newMode = currentMode === "dark" ? "light" : "dark"; 
  currentMode = newMode;
   setMode(newMode); 
}
</script>

<ModeWatcher />
<Sidebar.Root collapsible="icon" class="transition-none">
  <!-- Header -->
  <Sidebar.Header class="px-3 py-2">
    <div class="flex items-center justify-between w-full">
      {#if isOpen}
        <div class="flex items-center gap-2">
          <img 
            src={asset('/favicon.svg')} 
            alt="ShaderLab Logo" 
            class="w-5 h-5 dark:invert" 
          />
          <button onclick={toggleMode} class="font-semibold text-lg">ShaderLab</button>
        </div>
      {/if}
      
      <button
        onclick={handleToggle}
        class="rounded hover:bg-sidebar-accent transition-colors p-1 ml-auto"
        title={isOpen ? "Collapse sidebar" : "Expand sidebar"}
        aria-label={isOpen ? "Collapse sidebar" : "Expand sidebar"}
      >
        {#if isOpen}
          <PanelLeftClose class="w-4 h-4" />
        {:else}
          <PanelLeft class="w-4 h-4" />
        {/if}
      </button>
    </div>
  </Sidebar.Header>

  <!-- Content -->
  <Sidebar.Content class="flex-1">

      <!-- Home -->
  <Sidebar.Group>
    <Sidebar.Menu>
      <!-- Home MenuItem -->
      <Sidebar.MenuItem>
        <Sidebar.MenuButton 
          onclick={navigateToHome}
          isActive={isActive(resolve('/'))}
        >
          {#snippet child({ props })}
            <a href={resolve('/')} {...props}>
              <House class="w-4 h-4" />
              <span>Home</span>
            </a>
          {/snippet}
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>

      <!-- Tasks MenuItem -->
      <Sidebar.MenuItem>
        <Sidebar.MenuButton
          onclick={(e) => { e.preventDefault(); goto(resolve('/tasks')); }}
          isActive={isActive(resolve('/tasks'))}
        >
          {#snippet child({ props })}
            <a href={resolve('/tasks')} {...props}>
              <BookOpen class="w-4 h-4" />
              <span>Tasks</span>
            </a>
          {/snippet}
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  </Sidebar.Group>

    <!-- Tasks by Category -->
    {#each tasksByCategory as [category, categoryTasks]}
      <Collapsible.Root open class="group/collapsible">
        <Sidebar.Group>
          <Sidebar.GroupLabel>
            {#snippet child({ props })}
              <Collapsible.Trigger {...props}>
                <div class="flex items-center gap-2">
                  <BookOpen class="w-4 h-4" />
                  <span>{category}</span>
                </div>
                <ChevronDown
                  class="ml-auto w-4 h-4 transition-transform group-data-[state=open]/collapsible:rotate-180"
                />
              </Collapsible.Trigger>
            {/snippet}
          </Sidebar.GroupLabel>

          <Collapsible.Content>
            <Sidebar.GroupContent>
              <Sidebar.Menu>
                {#each categoryTasks as task}
                  {@const taskPath = resolve('/task/[title]', { title: task.title.toLowerCase() })}
                  <Sidebar.MenuItem>
                    <Sidebar.MenuButton
                      onclick={navigateToTask(task.title.toLowerCase())}
                      isActive={isActive(taskPath)}
                    >
                      {#snippet child({ props })}
                        <a href={taskPath} {...props}>
                          <BookOpen class="w-4 h-4" />
                          <span>{task.title}</span>
                        </a>
                      {/snippet}
                    </Sidebar.MenuButton>
                  </Sidebar.MenuItem>
                {/each}
              </Sidebar.Menu>
            </Sidebar.GroupContent>
          </Collapsible.Content>
        </Sidebar.Group>
      </Collapsible.Root>
    {/each}
  </Sidebar.Content>

  <!-- Footer -->
  <Sidebar.Footer>
    <Sidebar.Menu>
      <Sidebar.MenuItem>
        <Sidebar.MenuButton>
          {#snippet child({ props })}
            <div {...props}>
              <UserRound class="w-4 h-4" />
              {#if isOpen}
                <span>Marcel</span>
              {/if}
              <ChevronUp class="ml-auto w-4 h-4" />
            </div>
          {/snippet}
        </Sidebar.MenuButton>
      </Sidebar.MenuItem>
    </Sidebar.Menu>
  </Sidebar.Footer>

  <!-- Sidebar Rail (hover to expand when collapsed) -->
  <Sidebar.Rail />
</Sidebar.Root>

// src/components/Sidebar.tsx
"use client"

import * as React from "react"
import {
  Sidebar,
  SidebarContent,
  SidebarGroup,
  SidebarGroupContent,
  SidebarGroupLabel,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  SidebarHeader,
  SidebarFooter,
  SidebarRail,
  useSidebar,
} from "@/components/ui/sidebar"
import { Home, BookOpen, User2, ChevronUp, ChevronDown, PanelLeftClose, PanelLeft } from "lucide-react"
import { useNavigate } from "react-router-dom"
import lessonsData from "@/data/lessons.json"
import { Collapsible, CollapsibleTrigger, CollapsibleContent } from "@/components/ui/collapsible"

// Group lessons by category
const groupLessonsByCategory = (lessons: typeof lessonsData.lessons) => {
  return lessons.reduce((acc, lesson) => {
    const category = lesson.category || "Uncategorized"
    if (!acc[category]) acc[category] = []
    acc[category].push(lesson)
    return acc
  }, {} as Record<string, typeof lessonsData.lessons>)
}

export const AppSidebar = () => {
  const navigate = useNavigate()
  const { open, toggleSidebar } = useSidebar()
  const lessonsByCategory = groupLessonsByCategory(lessonsData.lessons)

  return (
    <Sidebar collapsible="icon" className="transition-none panel">
      {/* Header */}
      <SidebarHeader className="px-3 py-2">
        <div className="flex items-center justify-between">
          {open && (
            <div className="flex items-center gap-2">
              <img src="./favicon.ico" alt="Logo" className="w-5 h-5 dark:invert" />
              <span className="font-semibold text-lg">ShaderLab</span>
            </div>
          )}
          <button
            onClick={toggleSidebar}
            className="rounded hover:bg-sidebar-accent transition-colors"
            title={open ? "Collapse sidebar" : "Expand sidebar"}
          >
            {open ? <PanelLeftClose className="p-1" /> : <PanelLeft className="p-1" />}
          </button>
        </div>
      </SidebarHeader>

      {/* Content */}
      <SidebarContent className="flex-1">
        {/* Home */}
        <SidebarGroup>
            <SidebarMenu>
              <SidebarMenuItem>
                <SidebarMenuButton asChild>
                  <a
                    href="/"
                    onClick={(e) => {
                      e.preventDefault()
                      navigate("/")
                    }}
                  >
                    <Home className="w-4 h-4" />
                    <span>Übersicht</span>
                  </a>
                </SidebarMenuButton>
              </SidebarMenuItem>
            </SidebarMenu>
        </SidebarGroup>

        {/* Lessons by Category */}
        {Object.entries(lessonsByCategory).map(([category, lessons]) => {
          return (
            <Collapsible key={category} defaultOpen className="group/collapsible">
              <SidebarGroup>
                <SidebarGroupLabel asChild>
                  <CollapsibleTrigger className="flex items-center justify-between w-full">
                    <div className="flex items-center gap-2">
                      {/* Always show the category text/icon */}
                      <BookOpen className="w-4 h-4" />
                      <span>{category}</span>
                    </div>
                    <ChevronDown className="ml-auto w-4 h-4 transition-transform group-data-[state=open]/collapsible:rotate-180" />
                  </CollapsibleTrigger>
                </SidebarGroupLabel>

                <CollapsibleContent>
                  <SidebarGroupContent>
                    <SidebarMenu>
                      {lessons.map((lesson) => (
                        <SidebarMenuItem key={lesson.title}>
                          <SidebarMenuButton asChild>
                            <a
                              href={`/task/${lesson.title.toLowerCase()}`}
                              onClick={(e) => {
                                e.preventDefault()
                                navigate(`/task/${lesson.title.toLowerCase()}`)
                              }}
                            >
                              <BookOpen />
                              <span>{lesson.title}</span>
                            </a>
                          </SidebarMenuButton>
                        </SidebarMenuItem>
                      ))}
                    </SidebarMenu>
                  </SidebarGroupContent>
                </CollapsibleContent>
              </SidebarGroup>
            </Collapsible>
          )
        })}
      </SidebarContent>

      {/* Footer */}
      <SidebarFooter>
        <SidebarMenu>
          <SidebarMenuItem>
            <SidebarMenuButton>
              <User2 className="w-4 h-4" />
              {open && <span>Marcel</span>}
              <ChevronUp className="ml-auto w-4 h-4" />
            </SidebarMenuButton>
          </SidebarMenuItem>
        </SidebarMenu>
      </SidebarFooter>

      {/* SidebarRail for collapsing */}
      <SidebarRail />
    </Sidebar>
  )
}
