// src/components/MonacoEditor.tsx
  import { useRef, useState, useEffect, useCallback } from "react";
  import Editor, { BeforeMount, OnMount } from "@monaco-editor/react";
  import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
  import { Button } from "@/components/ui/button";
  import {
    Dialog,
    DialogContent,
    DialogFooter,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
  } from "@/components/ui/dialog";
  import * as monaco from "monaco-editor";
  import type { languages } from "monaco-editor";
  import { useLessonContext } from "@/contexts/LessonContext";

  /* ---------------------------- GLSL Language Setup ---------------------------- */
  const conf: languages.LanguageConfiguration = {
    comments: { lineComment: "//", blockComment: ["/*", "*/"] },
    brackets: [
      ["{", "}"],
      ["[", "]"],
      ["(", ")"],
    ],
    autoClosingPairs: [
      { open: "[", close: "]" },
      { open: "{", close: "}" },
      { open: "(", close: ")" },
      { open: "'", close: "'", notIn: ["string", "comment"] },
      { open: '"', close: '"', notIn: ["string"] },
    ],
  };

  const keywords = [
      'const','uniform','break','continue','do','for','while','if','else',
      'switch','case','in','out','inout','true','false','invariant','discard',
      'return','sampler2D','samplerCube','sampler3D','struct','radians','degrees',
      'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'pow', 'sinh', 'cosh', 'tanh',
      'asinh', 'acosh', 'atanh', 'exp', 'log', 'exp2', 'log2', 'sqrt', 'inversesqrt',
      'abs', 'sign', 'floor', 'ceil', 'round', 'roundEven', 'trunc', 'fract', 'mod',
      'modf', 'min', 'max', 'clamp', 'mix', 'step', 'smoothstep', 'length', 'distance',
      'dot', 'cross', 'determinant', 'inverse', 'normalize', 'faceforward', 'reflect',
      'refract', 'matrixCompMult', 'outerProduct', 'transpose', 'lessThan', 'lessThanEqual',
      'greaterThan', 'greaterThanEqual', 'equal', 'notEqual', 'any', 'all', 'not',
      'packUnorm2x16', 'unpackUnorm2x16', 'packSnorm2x16', 'unpackSnorm2x16',
      'packHalf2x16', 'unpackHalf2x16', 'dFdx', 'dFdy', 'fwidth', 'textureSize',
      'texture', 'textureProj', 'textureLod', 'textureGrad', 'texelFetch',
      'texelFetchOffset', 'textureProjLod', 'textureLodOffset', 'textureGradOffset',
      'textureProjLodOffset', 'textureProjGrad', 'intBitsToFloat', 'uintBitsToFloat',
      'floatBitsToInt', 'floatBitsToUint', 'isnan', 'isinf',
      'vec2', 'vec3', 'vec4', 'ivec2', 'ivec3', 'ivec4', 'uvec2', 'uvec3', 'uvec4',
      'bvec2', 'bvec3', 'bvec4', 'mat2', 'mat3', 'mat2x2', 'mat2x3', 'mat2x4', 'mat3x2',
      'mat3x3', 'mat3x4', 'mat4x2', 'mat4x3', 'mat4x4', 'mat4', 'float', 'int', 'uint',
      'void', 'bool',
  ];

  const language: languages.IMonarchLanguage = {
      tokenPostfix: '.glsl',
      defaultToken: 'invalid',
    keywords,
      operators: [
        '=', '>', '<', '!', '~', '?', ':', '==', '<=', '>=', '!=', '&&', '||',
        '++', '--', '+', '-', '*', '/', '&', '|', '^', '%', '<<', '>>', '>>>',
        '+=', '-=', '*=', '/=', '&=', '|=', '^=', '%=', '<<=', '>>=', '>>>='
      ],
      symbols: /[=><!~?:&|+\-*\/\^%]+/,
    tokenizer: {
      root: [
          [/[a-zA-Z_]\w*/, { cases: { '@keywords': 'keyword', '@default': 'identifier' } }],
          [/^\s*#\s*\w+/, 'keyword.directive'],
          { include: '@whitespace' },
          [/[{}()\[\]]/, '@brackets'],
          [/@symbols/, { cases: { '@operators': 'operator', '@default': '' } }],
          [/\d*\.\d+([eE][\-+]?\d+)?/, 'number.float'],
          [/\d+/, 'number'],
          [/[;,.]/, 'delimiter']
      ],
      whitespace: [
          [/[ \t\r\n]+/, 'white'],
          [/\/\*/, 'comment', '@comment'],
          [/\/\/.*$/, 'comment']
      ],
      comment: [
          [/[^\/*]+/, 'comment'],
          [/\/\*/, 'comment', '@push'],
          ['\\*/', 'comment', '@pop'],
          [/[\/*]/, 'comment']
        ]
      }
  };

  /* ------------------------------ Component ------------------------------ */
  export const MonacoEditor = () => {
    const {
      lesson,
      vertexShader,
      fragmentShader,
      setVertexShader,
      setFragmentShader,
      shaderErrors,
    } = useLessonContext();

    const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);
    const monacoRef = useRef<typeof monaco | null>(null);
    const decorations = useRef<string[]>([]);

    const [activeTab, setActiveTab] = useState(lesson.type === "2D" ? "fragment" : "vertex");
    const [showErrorConsole, setShowErrorConsole] = useState(false);
    const [errorList, setErrorList] = useState<typeof shaderErrors>([]);

    // Dark mode detection
    const [isDark, setIsDark] = useState(false);
    useEffect(() => {
      const root = window.document.documentElement;
      setIsDark(root.classList.contains("dark"));
      const observer = new MutationObserver(() => {
        setIsDark(root.classList.contains("dark"));
      });
      observer.observe(root, { attributes: true, attributeFilter: ["class"] });
      return () => observer.disconnect();
    }, []);

    /* ---------------------- GLSL Setup ---------------------- */
    const handleBeforeMount: BeforeMount = (monacoInstance) => {
      monacoRef.current = monacoInstance;
      if (!monacoInstance.languages.getLanguages().some((l) => l.id === "glsl")) {
        monacoInstance.languages.register({ id: "glsl" });
        monacoInstance.languages.setMonarchTokensProvider("glsl", language);
        monacoInstance.languages.setLanguageConfiguration("glsl", conf);
      }
    };

    const handleEditorMount: OnMount = (editor) => {
      editorRef.current = editor;
    };

    /* ---------------------- Apply Shader Errors ---------------------- */
    const applyShaderErrors = useCallback(() => {
      if (!monacoRef.current || !editorRef.current) return;
      const m = monacoRef.current;
      const ed = editorRef.current;

      // Clear old decorations
      decorations.current = ed.deltaDecorations(decorations.current, []);
      const model = ed.getModel();
      if (model) m.editor.setModelMarkers(model, "shader", []);

      const relevantErrors = shaderErrors.filter((e) => e.type === activeTab);
      if (relevantErrors.length === 0) return;

      const decos = relevantErrors.map((err) => ({
        range: new m.Range(err.line, 1, err.line, 1),
        options: {
          isWholeLine: true,
          className: "shader-error-line",
          glyphMarginClassName: "shader-error-glyph",
          hoverMessage: { value: err.message },
        },
      }));

      decorations.current = ed.deltaDecorations([], decos);

      const markers = relevantErrors.map((err) => ({
        startLineNumber: err.line,
        startColumn: 1,
        endLineNumber: err.line,
        endColumn: Number.MAX_VALUE,
        message: err.message,
        severity: m.MarkerSeverity.Error,
      }));
      if (model) m.editor.setModelMarkers(model, "shader", markers);

      setErrorList(relevantErrors);
      setShowErrorConsole(relevantErrors.length > 0);
    }, [shaderErrors, activeTab]);

    useEffect(() => applyShaderErrors(), [applyShaderErrors]);

    /* ---------------------- Handle Change ---------------------- */
    const handleChange = (value?: string) => {
      if (activeTab === "vertex") setVertexShader(value || "");
      else setFragmentShader(value || "");

      if (!editorRef.current || !monacoRef.current) return;

      // Clear decorations while typing
      editorRef.current.deltaDecorations(decorations.current, []);
      const model = editorRef.current.getModel();
      if (model) monacoRef.current.editor.setModelMarkers(model, "shader", []);

      setErrorList([]);
      setShowErrorConsole(false);
    };

    /* ---------------------- Reset ---------------------- */
    const [openResetModal, setOpenResetModal] = useState(false);
    const handleReset = () => {
      if (activeTab === "vertex") setVertexShader(lesson.starterVertexShader);
      else setFragmentShader(lesson.starterFragmentShader);
      setOpenResetModal(false);
    };

    /* ---------------------- Current Value ---------------------- */
    const currentValue = activeTab === "vertex" ? vertexShader : fragmentShader;

    /* ------------------------------ JSX ------------------------------ */
    return (
      <div className="panel h-full flex flex-col">
        <Tabs value={activeTab} onValueChange={setActiveTab} className="flex flex-col flex-1 overflow-hidden">
          <TabsList className="w-full justify-start panel">
            {lesson.type === "3D" && <TabsTrigger value="vertex">vertex.glsl</TabsTrigger>}
            <TabsTrigger value="fragment">fragment.glsl</TabsTrigger>
          </TabsList>

          <div className="flex-1 min-h-0 flex flex-col overflow-hidden">
            <Editor
              height="100%"
              language="glsl"
              theme={isDark ? "vs-dark" : "vs-light"}
              value={currentValue}
              beforeMount={handleBeforeMount}
              onMount={handleEditorMount}
              onChange={handleChange}
              options={{ minimap: { enabled: false }, fontSize: 14, lineNumbers: "on", automaticLayout: true }}
            />

            {showErrorConsole && (
              <div className="bg-red-950 border-t border-red-800 p-2 max-h-32 overflow-y-auto text-xs font-mono text-red-200">
                <div className="flex items-center justify-between mb-1">
                  <span className="text-red-400 font-semibold">SHADER ERRORS ({errorList.length})</span>
                  <button onClick={() => setShowErrorConsole(false)} className="text-red-400 hover:text-red-300 text-xs">✕</button>
                </div>
                <div className="space-y-1">
                  {errorList.map((err, idx) => (
                    <div key={idx} className="flex gap-2">
                      <span className="text-red-400">[{err.type}:{err.line}]</span>
                      <span>{err.message}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </Tabs>

        {/* Fixed Button Bar */}
        <div className="p-1 flex justify-end">
          <Dialog open={openResetModal} onOpenChange={setOpenResetModal}>
            <DialogTrigger asChild>
              <Button variant="outline" size="sm">Reset</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Reset Code?</DialogTitle>
              </DialogHeader>
              <p className="py-2">
                Are you sure you want to reset the code? Any changes in the open Tab will be lost.
              </p>
              <DialogFooter className="flex justify-end gap-2">
                <Button variant="outline" onClick={() => setOpenResetModal(false)}>Cancel</Button>
                <Button onClick={handleReset}>Confirm Reset</Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>

        <style>{`
          .shader-error-line { background: rgba(255,0,0,0.08); }
          .shader-error-glyph { background: #ff4d4f; width: 3px !important; margin-left: 3px; }
        `}</style>
      </div>
    );
  };

// src/lib/components/MonacoEditor.svelte
<script lang="ts">
import { onMount, onDestroy, tick } from 'svelte';
import * as Tabs from "$lib/components/ui/tabs/index.js";
import { taskStore } from '$lib/stores/taskStore';
import { browser } from '$app/environment';

/* ---------------------------- GLSL Language Setup ---------------------------- */
const conf: import('monaco-editor').languages.LanguageConfiguration = {
  comments: { lineComment: "//", blockComment: ["/*", "*/"] },
  brackets: [["{","}"], ["[","]"], ["(",")"]],
  autoClosingPairs: [
    { open: "[", close: "]" },
    { open: "{", close: "}" },
    { open: "(", close: ")" },
    { open: "'", close: "'", notIn: ["string","comment"] },
    { open: '"', close: '"', notIn: ["string"] },
  ]
};

const keywords = [
  'const','uniform','break','continue','do','for','while','if','else',
  'switch','case','in','out','inout','true','false','invariant','discard',
  'return','sampler2D','samplerCube','sampler3D','struct','radians','degrees',
  'sin','cos','tan','asin','acos','atan','pow','sinh','cosh','tanh',
  'asinh','acosh','atanh','exp','log','exp2','log2','sqrt','inversesqrt',
  'abs','sign','floor','ceil','round','roundEven','trunc','fract','mod',
  'modf','min','max','clamp','mix','step','smoothstep','length','distance',
  'dot','cross','determinant','inverse','normalize','faceforward','reflect',
  'refract','matrixCompMult','outerProduct','transpose','lessThan','lessThanEqual',
  'greaterThan','greaterThanEqual','equal','notEqual','any','all','not',
  'packUnorm2x16','unpackUnorm2x16','packSnorm2x16','unpackSnorm2x16',
  'packHalf2x16','unpackHalf2x16','dFdx','dFdy','fwidth','textureSize',
  'texture','textureProj','textureLod','textureGrad','texelFetch',
  'texelFetchOffset','textureProjLod','textureLodOffset','textureGradOffset',
  'textureProjLodOffset','textureProjGrad','intBitsToFloat','uintBitsToFloat',
  'floatBitsToInt','floatBitsToUint','isnan','isinf',
  'vec2','vec3','vec4','ivec2','ivec3','ivec4','uvec2','uvec3','uvec4',
  'bvec2','bvec3','bvec4','mat2','mat3','mat2x2','mat2x3','mat2x4','mat3x2',
  'mat3x3','mat3x4','mat4x2','mat4x3','mat4x4','mat4','float','int','uint','void','bool',
];

const language: import('monaco-editor').languages.IMonarchLanguage = {
  tokenPostfix: '.glsl',
  defaultToken: 'invalid',
  keywords,
  operators: [
    '=', '>', '<', '!', '~', '?', ':', '==', '<=', '>=', '!=', '&&', '||',
    '++', '--', '+', '-', '*', '/', '&', '|', '^', '%', '<<', '>>', '>>>',
    '+=', '-=', '*=', '/=', '&=', '|=', '^=', '%=', '<<=', '>>=', '>>>='
  ],
  symbols: /[=><!~?:&|+\-*\/\^%]+/,
  tokenizer: {
    root: [
      [/[a-zA-Z_]\w*/, { cases: { '@keywords': 'keyword', '@default': 'identifier' } }],
      [/^\s*#\s*\w+/, 'keyword.directive'],
      { include: '@whitespace' },
      [/[{}()\[\]]/, '@brackets'],
      [/@symbols/, { cases: { '@operators': 'operator', '@default': '' } }],
      [/\d*\.\d+([eE][\-+]?\d+)?/, 'number.float'],
      [/\d+/, 'number'],
      [/[;,.]/, 'delimiter']
    ],
    whitespace: [
      [/[ \t\r\n]+/, 'white'],
      [/\/\*/, 'comment', '@comment'],
      [/\/\/.*$/, 'comment']
    ],
    comment: [
      [/[^\/*]+/, 'comment'],
      [/\/\*/, 'comment', '@push'],
      ['\\*/', 'comment', '@pop'],
      [/[\/*]/, 'comment']
    ]
  }
};

/* ---------------------------- Component ---------------------------- */
let editorContainer: HTMLDivElement;
let editor: import('monaco-editor').editor.IStandaloneCodeEditor | null = null;
let monaco: typeof import('monaco-editor') | null = null;
let darkObserver: MutationObserver | null = null;

let vertexModel: import('monaco-editor').editor.ITextModel | null = null;
let fragmentModel: import('monaco-editor').editor.ITextModel | null = null;

let isDark = false;
let decorations: string[] = [];
let showErrorConsole = false;
type ShaderError = { type: 'vertex' | 'fragment', line: number, message: string };
let errorList: ShaderError[] = [];

// Subscribe to store
let storeState = { 
  task: null, 
  vertexShader: '', 
  fragmentShader: '', 
  activeTab: 'fragment' as 'vertex' | 'fragment'
};

const unsubscribe = taskStore.subscribe(state => {
  storeState = state;
});

/* ---------------------------- Reactive values ---------------------------- */
$: task = storeState.task;
$: vertexShader = storeState.vertexShader;
$: fragmentShader = storeState.fragmentShader;
$: currentTab = storeState.activeTab;
$: shaderErrors = (storeState as any).shaderErrors || [];

/* ---------------------------- Methods ---------------------------- */
function handleChange(value: string) {
  // Prevent infinite loops by checking if value actually changed
  const currentValue = currentTab === 'vertex' ? vertexShader : fragmentShader;
  if (value === currentValue) return;

  if (currentTab === 'vertex') {
    taskStore.setVertexShader(value);
  } else {
    taskStore.setFragmentShader(value);
  }

  if (editor && monaco) {
    decorations = editor.deltaDecorations(decorations, []);
    const model = editor.getModel();
    if (model) monaco.editor.setModelMarkers(model, "shader", []);
  }

  errorList = [];
  showErrorConsole = false;
}

function handleTabChange(newTab: 'vertex' | 'fragment') {
  taskStore.setActiveTab(newTab);
}

function applyShaderErrors() {
  if (!monaco || !editor) return;

  const model = editor.getModel();
  if (model) monaco.editor.setModelMarkers(model, "shader", []);
  decorations = editor.deltaDecorations(decorations, []);

  const relevantErrors = shaderErrors.filter(e => e.type === currentTab);
  if (relevantErrors.length === 0) {
    errorList = [];
    showErrorConsole = false;
    return;
  }

  const decos = relevantErrors.map(err => ({
    range: new monaco!.Range(err.line, 1, err.line, 1),
    options: {
      isWholeLine: true,
      className: "shader-error-line",
      glyphMarginClassName: "shader-error-glyph",
      hoverMessage: { value: err.message },
    }
  }));

  decorations = editor.deltaDecorations([], decos);

  const markers = relevantErrors.map(err => ({
    startLineNumber: err.line,
    startColumn: 1,
    endLineNumber: err.line,
    endColumn: Number.MAX_VALUE,
    message: err.message,
    severity: monaco.MarkerSeverity.Error
  }));

  if (model) monaco.editor.setModelMarkers(model, "shader", markers);

  errorList = relevantErrors;
  showErrorConsole = relevantErrors.length > 0;
}

/* ---------------------------- Lifecycle ---------------------------- */
onMount(async () => {
  await tick();
  if (!editorContainer || !browser) return;

  // Dark mode detection
  const root = document.documentElement;
  isDark = root.classList.contains("dark");
  darkObserver = new MutationObserver(() => {
    isDark = root.classList.contains("dark");
    editor?.updateOptions({ theme: isDark ? 'vs-dark' : 'vs-light' });
  });
  darkObserver.observe(root, { attributes: true, attributeFilter: ["class"] });

  monaco = await import('monaco-editor');

  (window as any).MonacoEnvironment = {
    getWorker: (_workerId: string, label: string) =>
      new Worker(new URL('monaco-editor/esm/vs/editor/editor.worker.js', import.meta.url), { type: 'module' })
  };

  if (!monaco.languages.getLanguages().some(l => l.id === "glsl")) {
    monaco.languages.register({ id: "glsl" });
    monaco.languages.setMonarchTokensProvider("glsl", language);
    monaco.languages.setLanguageConfiguration("glsl", conf);
  }

  vertexModel = monaco.editor.createModel(vertexShader, 'glsl', monaco.Uri.parse('inmemory://model/vertex.glsl'));
  fragmentModel = monaco.editor.createModel(fragmentShader, 'glsl', monaco.Uri.parse('inmemory://model/fragment.glsl'));

  editor = monaco.editor.create(editorContainer, {
    model: currentTab === 'vertex' ? vertexModel : fragmentModel,
    language: 'glsl',
    theme: isDark ? 'vs-dark' : 'vs-light',
    minimap: { enabled: false },
    fontSize: 14,
    lineNumbers: 'on',
    automaticLayout: true
  });

  editor.onDidChangeModelContent(() => {
    const value = editor!.getValue();
    handleChange(value);
  });

  applyShaderErrors();
});

// Switch model when tab changes
$: if (editor && vertexModel && fragmentModel) {
  const model = currentTab === 'vertex' ? vertexModel : fragmentModel;
  if (editor.getModel() !== model) {
    const pos = editor.getPosition();
    editor.setModel(model);
    if (pos) editor.setPosition(pos);
    editor.focus();
  }
}

// Sync editor models with store
$: if (vertexModel && vertexShader !== vertexModel.getValue()) {
  const pos = editor?.getPosition();
  vertexModel.setValue(vertexShader);
  if (pos && editor && currentTab === 'vertex') {
    editor.setPosition(pos);
  }
}

$: if (fragmentModel && fragmentShader !== fragmentModel.getValue()) {
  const pos = editor?.getPosition();
  fragmentModel.setValue(fragmentShader);
  if (pos && editor && currentTab === 'fragment') {
    editor.setPosition(pos);
  }
}

// Apply errors when they change
$: if (editor && monaco) {
  applyShaderErrors();
}

onDestroy(() => {
  editor?.dispose();
  vertexModel?.dispose();
  fragmentModel?.dispose();
  darkObserver?.disconnect();
  unsubscribe();
});
</script>

<div class="panel h-full flex flex-col">
<Tabs.Root
  value={currentTab}
  onValueChange={handleTabChange}
  class="flex flex-col flex-1 min-h-0 overflow-hidden"
>
 <!-- Tab triggers -->
<Tabs.List class="h-10 justify-start bg-transparent border-none p-0 gap-0">
    {#if task?.type === '3D'}
    <Tabs.Trigger
        value="vertex"
        class="h-10 px-4 data-[state=active]:bg-background hover:bg-muted/50 transition-colors"
    >
        vertex.glsl
    </Tabs.Trigger>
    {/if}
    <Tabs.Trigger
    value="fragment"
    class="h-10 px-4 data-[state=active]:bg-background hover:bg-muted/50 transition-colors"
    >
    fragment.glsl
    </Tabs.Trigger>
</Tabs.List>

    <div class="flex-1 min-h-0 flex flex-col overflow-hidden">
      <div bind:this={editorContainer} class="flex-1 w-full relative"></div>

      {#if showErrorConsole}
      <div class="bg-red-950 border-t border-red-800 p-2 max-h-32 overflow-y-auto text-xs font-mono text-red-200">
        <div class="flex items-center justify-between mb-1">
          <span class="text-red-400 font-semibold">SHADER ERRORS ({errorList.length})</span>
          <button on:click={() => (showErrorConsole = false)} class="text-red-400 hover:text-red-300 text-xs">✕</button>
        </div>
        <div class="space-y-1">
          {#each errorList as err, idx (idx)}
            <div class="flex gap-2">
              <span class="text-red-400">[{err.type}:{err.line}]</span>
              <span>{err.message}</span>
            </div>
          {/each}
        </div>
      </div>
      {/if}
    </div>
  </Tabs.Root>
</div>

<style>
:global(.shader-error-line) { background: rgba(255,0,0,0.08); }
:global(.shader-error-glyph) { background: #ff4d4f; width: 3px !important; margin-left: 3px; }
</style>
